name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^6.2.12



  get: ^4.6.6
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  flutter_cart: ^0.0.9
  get_storage: ^2.1.1
  flutter_login: ^4.2.1
  webview_flutter: ^4.7.0
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.6
  onesignal_flutter: ^5.1.6
  google_sign_in: ^6.1.4
  image_picker: ^1.0.7
  http: ^1.2.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  easy_localization: ^3.0.3



flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/
    - assets/images/apple_warranty_banner.jpg
    - assets/translations/




